In [1]:
import os
import pandas as pd
from bs4 import BeautifulSoup

# Define the folder path containing the HTML files
folder_path = 'C:\\Users\\hp\\Documents\\data\\data\\Balance Sheets'

# Initialize an empty list to store the extracted text
text_list = []

# Loop through each file in the folder
for filename in os.listdir(folder_path):
    if filename.endswith('.html'):
        file_path = os.path.join(folder_path, filename)
        
        # Open and read the content of the HTML file
        with open(file_path, 'r', encoding='utf-8') as file:
            content = file.read()
        
        # Parse the HTML content using BeautifulSoup
        soup = BeautifulSoup(content, 'html.parser')
        
        # Extract the relevant text from the HTML
        # Example: Extract all text from the HTML body
        body = soup.find('body')
        if body:
            text = body.get_text(separator=' ', strip=True)
            
            c_filename = filename.replace('.html', '')
            
            # Append the serial number, category, filename, and extracted text to the list
            text_list.append({
                'filename': c_filename,
                'text': text,
                'file_type': 'Balance Sheets'
            })
            

# Convert the list of extracted text to a DataFrame
balance_sheets_df = pd.DataFrame(text_list)

In [2]:
balance_sheets_df

filename                                               text  \
0     18320959_3  (7 in lacs) (7 in lacs) _1_ Standalone Consoli...   
1     18391125_2  Consolidated Standalone Particulars As at As a...   
2     18442877_5  Standalone Consolidated Audited Audited Partic...   
3     18445487_2  GUJARAT NARMADA VALLEY FERTILIZERS & CHEMICALS...   
4     18445494_3  Standalone Consolidated As at As at As at As a...   
..           ...                                                ...   
265  18964857_12  Particulars As at March 31, 2018 As at March 3...   
266   18964857_3  Notes to standalone I ml AS financial results ...   
267   18964858_3  STANDALONE | CONSOLIDATED As at As at As at As...   
268   19213523_2  As at March 31, 2018 (Audited) As at March 31,...   
269   19213523_3  As at March 31, 2018 (Audited) As at March 31,...   

          file_type  
0    Balance Sheets  
1    Balance Sheets  
2    Balance Sheets  
3    Balance Sheets  
4    Balance Sheets  
..              ...  
265  Balance Sheets  
266  Balance Sheets  
267  Balance Sheets  
268  Balance Sheets  
269  Balance Sheets  

[270 rows x 3 columns]

In [3]:
import os
import pandas as pd
from bs4 import BeautifulSoup

# Define the folder path containing the HTML files
folder_path = 'C:\\Users\\hp\\Documents\\data\\data\\Cash Flow'

# Initialize an empty list to store the extracted text
text_list = []

# Loop through each file in the folder
for filename in os.listdir(folder_path):
    if filename.endswith('.html'):
        file_path = os.path.join(folder_path, filename)
        
        try:
            # Open and read the content of the HTML file
            with open(file_path, 'r', encoding='utf-8') as file:
                content = file.read()
            
            # Parse the HTML content using BeautifulSoup
            soup = BeautifulSoup(content, 'html.parser')
            
            # Extract text from tables
            tables = soup.find_all('table')
            for table in tables:
                text = table.get_text(separator=' ', strip=True)
                
                c_filename = filename.replace('.html', '')
                
                # Append the filename and extracted text to the list
                text_list.append({
                    'filename': c_filename,
                    'text': text,
                    'file_type': 'Cash Flow'
                })
        except Exception as e:
            print(f"Error processing file '{filename}': {e}")

# Convert the list of extracted text to a DataFrame
cash_flow_df = pd.DataFrame(text_list)

In [4]:
cash_flow_df

filename                                               text  \
0          18460658_57  Particulars Quarter Ended Year Ended Mar-18 Ma...   
1          18563939_11  Cash flows from operating activities Net incom...   
2          18563939_13  Cash flows from financing activities (Decrease...   
3          18563939_14  Deposits with banks, having maturities less th...   
4   18599651_table_100  Particulars For the year ended December 31, 20...   
5   18599651_table_161  Particulars For year ended cember 31, 2017 For...   
6    18600361_table_65  DESCRIPTION Year Ended March 31, 2017 Year End...   
7    18612942_table_29  PARTICULARS As on 31/03/2017 As on 31/03/2016 ...   
8    18630219_table_52  B. CASH FLOW FROM INVESTING ACTIVITIES: Fixed ...   
9   18630222_table_135  Particulars Year ended December 31, 2017 Year ...   
10  18630222_table_137  Particulars Year ended Year ended December 31,...   
11   18630222_table_73  Particulars Year ended December 31, 2017 Year ...   
12   18646837_table_63  Particulars Year ended December 31, 2017 Year ...   
13   18646837_table_64  Particulars Year ended December 31, 2017 Year ...   
14   18646845_table_52  For the year ended 31 st December 2017 31 Dece...   
15   18646845_table_53  31 December 2017 INR in Lacs 31 December 2016 ...   
16   18661963_table_36  Rs. In lakhs Rs. In lakhs Particulars As at 31...   
17   18661964_table_39  CASH FLOW STATEMENT FOR THE YEAR ENDED 31ST MA...   
18   18661965_table_39  Particulars Year Ended 31.03.2017 Rs. Year End...   
19   18699662_table_26  Standalone Consolidated 2017 2016 2017 2016 A ...   
20   18731570_table_44  Year ended December 31, 2017 ( ' ) Year ended ...   
21   18731570_table_45  As at December 31, 2017 ( ' ) As at December 3...   
22   18731570_table_94  Year ended December 31, 2017 ( ' ) Year ended ...   
23   18731571_table_52  Particulars For the year ended December 31, 20...   
24   18731571_table_53  Particulars For the year ended December 31, 20...   
25  18779279_table_166  2018 2017 A Cash flow from operating activitie...   
26  18779279_table_167  2018 2017 C Cash flow from financing activitie...   
27  18779279_table_293  2018 2017 C. Cash flow from financing activiti...   
28  18888243_table_154  For the Year For the Year ended on ended on 31...   
29  19058355_table_139  (INR in Crores) Particulars For the year ended...   
30  19058356_table_173  Year ended 31st March, 2018 Year ended 31st Ma...   
31  19058356_table_174  Year ended 31st March, 2018 Year ended 31st Ma...   
32   19058356_table_61  Particulars Year ended 31st March, 2018 Year e...   
33  19070958_table_167  CASH FLOW FROM OPERATING ACTIVITIES: Profit be...   
34  19073396_table_216  2017-18 2016-17 A: CASH FLOW FROM OPERATING AC...   
35  19442329_table_127  Notes Year ended 31-Mar-2018 Year ended 31-Mar...   

    file_type  
0   Cash Flow  
1   Cash Flow  
2   Cash Flow  
3   Cash Flow  
4   Cash Flow  
5   Cash Flow  
6   Cash Flow  
7   Cash Flow  
8   Cash Flow  
9   Cash Flow  
10  Cash Flow  
11  Cash Flow  
12  Cash Flow  
13  Cash Flow  
14  Cash Flow  
15  Cash Flow  
16  Cash Flow  
17  Cash Flow  
18  Cash Flow  
19  Cash Flow  
20  Cash Flow  
21  Cash Flow  
22  Cash Flow  
23  Cash Flow  
24  Cash Flow  
25  Cash Flow  
26  Cash Flow  
27  Cash Flow  
28  Cash Flow  
29  Cash Flow  
30  Cash Flow  
31  Cash Flow  
32  Cash Flow  
33  Cash Flow  
34  Cash Flow  
35  Cash Flow

In [5]:
# Define the folder path containing the HTML files
folder_path = 'C:\\Users\\hp\\Documents\\data\\data\\Income Statement'

# Initialize an empty list to store the extracted text
text_list = []

# Loop through each file in the folder
for filename in os.listdir(folder_path):
    if filename.endswith('.html'):
        file_path = os.path.join(folder_path, filename)
        
        try:
            # Open and read the content of the HTML file
            with open(file_path, 'r', encoding='utf-8') as file:
                content = file.read()
            
            # Parse the HTML content using BeautifulSoup
            soup = BeautifulSoup(content, 'html.parser')
            
            # Extract text from tables
            tables = soup.find_all('table')
            for table in tables:
                text = table.get_text(separator=' ', strip=True)
                
                c_filename = filename.replace('.html', '')
                
                # Append the filename and extracted text to the list
                text_list.append({
                    'filename': c_filename,
                    'text': text,
                    'file_type': 'Income Statement'
                })
        except Exception as e:
            print(f"Error processing file '{filename}': {e}")

# Convert the list of extracted text to a DataFrame
income_statement_df = pd.DataFrame(text_list)

In [6]:
income_statement_df

filename                                               text  \
0     18445487_1  Corresponding Year to date Year to date Preced...   
1     18445494_1  Particulars Quarter Ended Year Ended Year Ende...   
2     18445494_2  Consolidated Particulars Year ended 31/03/2018...   
3     18448274_1  Standalone Quarter Ended Year Ended Sr No. Par...   
4     18448274_3  Sr No. Consolidated Particulars Quarter Ended ...   
..           ...                                                ...   
300   18964857_1  Quarter ended Year ended S.No. Particulars Mar...   
301  18964857_10  (In Rs. crore) Particulars Quarter ended Year ...   
302   18964857_9  1*111 titulars Quarter ended Year ended March ...   
303   18964858_1  51. No Particulars 31 st March 2018 31 st Dece...   
304   19213523_1  SL NO. PARTICULARS QUARTER ENDED YEAR ENDED 31...   

            file_type  
0    Income Statement  
1    Income Statement  
2    Income Statement  
3    Income Statement  
4    Income Statement  
..                ...  
300  Income Statement  
301  Income Statement  
302  Income Statement  
303  Income Statement  
304  Income Statement  

[305 rows x 3 columns]

In [7]:
# Define the folder path containing the HTML files
folder_path = 'C:\\Users\\hp\\Documents\\data\\data\\Notes'

# Initialize an empty list to store the extracted text
text_list = []

# Loop through each file in the folder
for filename in os.listdir(folder_path):
    if filename.endswith('.html'):
        file_path = os.path.join(folder_path, filename)
        
        try:
            # Open and read the content of the HTML file
            with open(file_path, 'r', encoding='utf-8') as file:
                content = file.read()
            
            # Parse the HTML content using BeautifulSoup
            soup = BeautifulSoup(content, 'html.parser')
            
            # Extract text from tables
            tables = soup.find_all('table')
            for table in tables:
                text = table.get_text(separator=' ', strip=True)
                
                c_filename = filename.replace('.html', '')
                
                # Append the filename and extracted text to the list
                text_list.append({
                    'filename': c_filename,
                    'text': text,
                    'file_type': 'Notes'
                })
        except Exception as e:
            print(f"Error processing file '{filename}': {e}")

# Convert the list of extracted text to a DataFrame
notes_df = pd.DataFrame(text_list)

In [8]:
notes_df

filename                                               text  \
0    18599651_table_105  Name of the Entity Country of Incorporation Ne...   
1    18599651_table_107  1 Hexaware Technologies Limited (Parent) Wholl...   
2    18599651_table_108  Particulars Freehold Land Buildings Plant and ...   
3    18599651_table_109  As at January 1, 2016 1,715.34 Translation exc...   
4    18599651_table_110  7 Intangible assets Intangible assets consist ...   
..                  ...                                                ...   
685   19119447_table_72  Particulars As at 31.03.2018 As at 31.03.2017 ...   
686   19119447_table_73  Particulars As at 31.03.2018 As at 31.03.2017 ...   
687   19119447_table_74  Particulars As at 31.03.2018 As at 31.03.2017 ...   
688   19119447_table_76  Particulars As at 31.03.2018 As at 31.03.2017 ...   
689   19119447_table_78  Particulars As at 31.03.2018 As at 31.03.2017 ...   

    file_type  
0       Notes  
1       Notes  
2       Notes  
3       Notes  
4       Notes  
..        ...  
685     Notes  
686     Notes  
687     Notes  
688     Notes  
689     Notes  

[690 rows x 3 columns]

In [9]:
# Define the folder path containing the HTML files
folder_path = 'C:\\Users\\hp\\Documents\\data\\data\\Others'

# Initialize an empty list to store the extracted text
text_list = []

# Loop through each file in the folder
for filename in os.listdir(folder_path):
    if filename.endswith('.html'):
        file_path = os.path.join(folder_path, filename)
        
        try:
            # Open and read the content of the HTML file
            with open(file_path, 'r', encoding='utf-8') as file:
                content = file.read()
            
            # Parse the HTML content using BeautifulSoup
            soup = BeautifulSoup(content, 'html.parser')
            
            # Extract text from tables
            tables = soup.find_all('table')
            for table in tables:
                text = table.get_text(separator=' ', strip=True)
                
                c_filename = filename.replace('.html', '')
                
                # Append the filename and extracted text to the list
                text_list.append({
                    'filename': c_filename,
                    'text': text,
                    'file_type': 'Others'
                })
        except Exception as e:
            print(f"Error processing file '{filename}': {e}")

# Convert the list of extracted text to a DataFrame
others_df = pd.DataFrame(text_list)

In [10]:
others_df

filename                                               text file_type
0     18320959_2  8 Remeasurement cost of net defined benefit li...    Others
1     18362675_2  Particulars Consolidated Standalone 3 Months e...    Others
2     18362675_3  Particulars Consolidated Standalone Forex gain...    Others
3     18380714_1  1 Quarter Jan Mar 2018 Quarter Jan-Mar 2017 | ...    Others
4     18391125_3  Name of the Company Country of Incorporation N...    Others
...          ...                                                ...       ...
1219  18964858_6  1. Singhi & Co., 2. Chatterjee & Co., 3. V.K. ...    Others
1220  18964858_7  Singhi & Co. Chatterjee &Co. V.K. Dhingra & Co...    Others
1221  18964858_8  r* • • *“•" 1 1 i • • 1 1 1 STEEL AUTHORITY OF...    Others
1222  19213523_4  Particulars Quarter ended Year ended March 31,...    Others
1223  19213523_5  Particulars Quarter Ended Year Ended March 31,...    Others

[1224 rows x 3 columns]

In [11]:
print("Shape of balance_sheets_df:", balance_sheets_df.shape)
print("Shape of cash_flow_df:", cash_flow_df.shape)
print("Shape of income_statement_df:", income_statement_df.shape)
print("Shape of notes_df:", notes_df.shape)
print("Shape of others_df:", others_df.shape)

Shape of balance_sheets_df: (270, 3)
Shape of cash_flow_df: (36, 3)
Shape of income_statement_df: (305, 3)
Shape of notes_df: (690, 3)
Shape of others_df: (1224, 3)


In [12]:
df = pd.concat([balance_sheets_df, cash_flow_df, income_statement_df, notes_df, others_df], ignore_index=True)

In [13]:
df

filename                                               text  \
0     18320959_3  (7 in lacs) (7 in lacs) _1_ Standalone Consoli...   
1     18391125_2  Consolidated Standalone Particulars As at As a...   
2     18442877_5  Standalone Consolidated Audited Audited Partic...   
3     18445487_2  GUJARAT NARMADA VALLEY FERTILIZERS & CHEMICALS...   
4     18445494_3  Standalone Consolidated As at As at As at As a...   
...          ...                                                ...   
2520  18964858_6  1. Singhi & Co., 2. Chatterjee & Co., 3. V.K. ...   
2521  18964858_7  Singhi & Co. Chatterjee &Co. V.K. Dhingra & Co...   
2522  18964858_8  r* • • *“•" 1 1 i • • 1 1 1 STEEL AUTHORITY OF...   
2523  19213523_4  Particulars Quarter ended Year ended March 31,...   
2524  19213523_5  Particulars Quarter Ended Year Ended March 31,...   

           file_type  
0     Balance Sheets  
1     Balance Sheets  
2     Balance Sheets  
3     Balance Sheets  
4     Balance Sheets  
...              ...  
2520          Others  
2521          Others  
2522          Others  
2523          Others  
2524          Others  

[2525 rows x 3 columns]

In [14]:
import nltk
import re
from nltk.corpus import stopwords

# Download NLTK resources 
nltk.download('stopwords')

def clean_text(text):
    # Remove HTML tags
    text = BeautifulSoup(text, "html.parser").get_text()
    
    # Remove non-alphanumeric characters and convert to lowercase
    text = re.sub(r'[^a-zA-Z\s]', '', text.lower())
    
    # Tokenize the text
    tokens = nltk.word_tokenize(text)
    
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [token for token in tokens if token not in stop_words]
    
    # Join tokens back into a single string
    c_text = ' '.join(tokens)
    
    return c_text

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [15]:
df['clean_text'] = df['text'].apply(clean_text)

C:\Users\hp\AppData\Local\Temp\ipykernel_14332\1481641501.py:10: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  text = BeautifulSoup(text, "html.parser").get_text()


In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus=list(df['clean_text'].values)

tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the "clean_tweet" column to TF-IDF representation
tfidf = tfidf_vectorizer.fit_transform(corpus)

In [17]:
tfidf

<2525x10334 sparse matrix of type '<class 'numpy.float64'>'
	with 91091 stored elements in Compressed Sparse Row format>

In [18]:
df_tfidf = pd.DataFrame.sparse.from_spmatrix(tfidf)
df_tfidf.columns = tfidf_vectorizer.get_feature_names_out()
df_tfidf.index=df['text']

In [19]:
df_tfidf.head(2)

aa  aaa  aaand  aaar  \
text                                                                        
(7 in lacs) (7 in lacs) _1_ Standalone Consolid...  0.0  0.0    0.0   0.0   
Consolidated Standalone Particulars As at As at...  0.0  0.0    0.0   0.0   

                                                    aaastable  aac  aai  \
text                                                                      
(7 in lacs) (7 in lacs) _1_ Standalone Consolid...        0.0  0.0  0.0   
Consolidated Standalone Particulars As at As at...        0.0  0.0  0.0   

                                                    aakaash  aanya  \
text                                                                 
(7 in lacs) (7 in lacs) _1_ Standalone Consolid...      0.0    0.0   
Consolidated Standalone Particulars As at As at...      0.0    0.0   

                                                    aarliaprogrett  ...  zoo  \
text                                                                ...        
(7 in lacs) (7 in lacs) _1_ Standalone Consolid...             0.0  ...  0.0   
Consolidated Standalone Particulars As at As at...             0.0  ...  0.0   

                                                    zozila   zr  zrt   zs  \
text                                                                        
(7 in lacs) (7 in lacs) _1_ Standalone Consolid...     0.0  0.0  0.0  0.0   
Consolidated Standalone Particulars As at As at...     0.0  0.0  0.0  0.0   

                                                     zt  ztocehwup  zuir   zz  \
text                                                                            
(7 in lacs) (7 in lacs) _1_ Standalone Consolid...  0.0        0.0   0.0  0.0   
Consolidated Standalone Particulars As at As at...  0.0        0.0   0.0  0.0   

                                                    zzz  
text                                                     
(7 in lacs) (7 in lacs) _1_ Standalone Consolid...  0.0  
Consolidated Standalone Particulars As at As at...  0.0  

[2 rows x 10334 columns]

In [20]:
# Encode the target labels
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['target_category'] = label_encoder.fit_transform(df['file_type'])

In [21]:
df.head()

filename                                               text  \
0  18320959_3  (7 in lacs) (7 in lacs) _1_ Standalone Consoli...   
1  18391125_2  Consolidated Standalone Particulars As at As a...   
2  18442877_5  Standalone Consolidated Audited Audited Partic...   
3  18445487_2  GUJARAT NARMADA VALLEY FERTILIZERS & CHEMICALS...   
4  18445494_3  Standalone Consolidated As at As at As at As a...   

        file_type                                         clean_text  \
0  Balance Sheets  lacs lacs standalone consolidated sr particula...   
1  Balance Sheets  consolidated standalone particulars mar mar ma...   
2  Balance Sheets  standalone consolidated audited audited partic...   
3  Balance Sheets  gujarat narmada valley fertilizers chemicals l...   
4  Balance Sheets  standalone consolidated particulars equity lia...   

   target_category  
0                0  
1                0  
2                0  
3                0  
4                0

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [23]:
X_train, X_test, y_train, y_test = train_test_split(tfidf, df['target_category'], test_size=0.2, random_state=42)

In [24]:
X=tfidf
y=df['target_category']

In [25]:
X.shape,y.shape

((2525, 10334), (2525,))

In [26]:
y.value_counts()
#imbalance target

target_category
4    1224
3     690
2     305
0     270
1      36
Name: count, dtype: int64

In [27]:
from imblearn.combine import SMOTETomek

X_new,y_new= SMOTETomek().fit_resample(X,y)

In [28]:
X_new.shape,y_new.shape

((6114, 10334), (6114,))

In [29]:
y_new.value_counts()

target_category
0    1224
1    1224
2    1223
3    1222
4    1221
Name: count, dtype: int64

In [30]:
def accuracy_checking(X_data, y_data, algorithm):
  #train test splitting
  X_train, X_test, y_train, y_test= train_test_split(X_data, y_data, test_size= 0.2, random_state=42)

  model= algorithm().fit(X_train, y_train)

  y_pred_train= model.predict(X_train)
  y_pred_test= model.predict(X_test)

  #checking the accuracy_score
  accuracy_train= accuracy_score(y_train, y_pred_train)
  accuracy_test= accuracy_score(y_test, y_pred_test)

  metrics={"Algorithm": algorithm.__name__,
           "Accuracy_Train": accuracy_train,
           "Accuracy_Test": accuracy_test}
  return metrics

In [31]:
print(accuracy_checking(X_new,y_new,DecisionTreeClassifier))
print(accuracy_checking(X_new,y_new,RandomForestClassifier))
print(accuracy_checking(X_new,y_new,MultinomialNB))
print(accuracy_checking(X_new,y_new,KNeighborsClassifier))
print(accuracy_checking(X_new,y_new,SVC))

{'Algorithm': 'DecisionTreeClassifier', 'Accuracy_Train': 1.0, 'Accuracy_Test': 0.9591169255928046}
{'Algorithm': 'RandomForestClassifier', 'Accuracy_Train': 1.0, 'Accuracy_Test': 0.9754701553556827}
{'Algorithm': 'MultinomialNB', 'Accuracy_Train': 0.9208750766714373, 'Accuracy_Test': 0.8871627146361406}
{'Algorithm': 'KNeighborsClassifier', 'Accuracy_Train': 0.9578818237579227, 'Accuracy_Test': 0.9329517579721995}
{'Algorithm': 'SVC', 'Accuracy_Train': 0.9983643426702106, 'Accuracy_Test': 0.9836467702371219}


In [32]:
print(accuracy_checking(X_new,y_new,DecisionTreeClassifier))
print(accuracy_checking(X_new,y_new,RandomForestClassifier))
print(accuracy_checking(X_new,y_new,MultinomialNB))
print(accuracy_checking(X_new,y_new,KNeighborsClassifier))
print(accuracy_checking(X_new,y_new,SVC))

{'Algorithm': 'DecisionTreeClassifier', 'Accuracy_Train': 1.0, 'Accuracy_Test': 0.9582992641046607}
{'Algorithm': 'RandomForestClassifier', 'Accuracy_Train': 1.0, 'Accuracy_Test': 0.9771054783319706}
{'Algorithm': 'MultinomialNB', 'Accuracy_Train': 0.9208750766714373, 'Accuracy_Test': 0.8871627146361406}
{'Algorithm': 'KNeighborsClassifier', 'Accuracy_Train': 0.9578818237579227, 'Accuracy_Test': 0.9329517579721995}
{'Algorithm': 'SVC', 'Accuracy_Train': 0.9983643426702106, 'Accuracy_Test': 0.9836467702371219}


In [92]:
#SVC Classification report
from sklearn.metrics import accuracy_score,auc,roc_curve,confusion_matrix,classification_report

x_train, x_test, y_train, y_test= train_test_split(X_new, y_new, test_size= 0.2, random_state= 42)

model= SVC().fit(x_train,y_train)

y_pred_train= model.predict(x_train)
y_pred_test= model.predict(x_test)

#checking the accuracy_score for train and test

accuracy_train= accuracy_score(y_train, y_pred_train)
accuracy_test= accuracy_score(y_test, y_pred_test)

print("Accuracy score for Train and Test")
print(" ")
print("Accuracy_Train: ",accuracy_train)
print("Accuracy_Test: ",accuracy_test)
print("  ")
#confution matrics and the classification report for test

print("Confution_matrix for Test")
print(" ")
print(confusion_matrix(y_true= y_test, y_pred= y_pred_test))
print(" ")
print("Classification_report for Test")
print(" ")
print(classification_report(y_true= y_test, y_pred= y_pred_test))

Accuracy score for Train and Test
 
Accuracy_Train:  0.9983643426702106
Accuracy_Test:  0.9836467702371219
  
Confution_matrix for Test
 
[[259   0   0   0   0]
 [  0 229   0   0   0]
 [  0   0 240   0   2]
 [  0   0   0 236   7]
 [  1   0   3   7 239]]
 
Classification_report for Test
 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       259
           1       1.00      1.00      1.00       229
           2       0.99      0.99      0.99       242
           3       0.97      0.97      0.97       243
           4       0.96      0.96      0.96       250

    accuracy                           0.98      1223
   macro avg       0.98      0.98      0.98      1223
weighted avg       0.98      0.98      0.98      1223



In [91]:
#Random forrst classification report
x_train, x_test, y_train, y_test= train_test_split(X_new, y_new, test_size= 0.2, random_state= 42)

model= RandomForestClassifier(max_depth=20, max_features= None, min_samples_leaf=1, min_samples_split=2).fit(x_train,y_train)

y_pred_train= model.predict(x_train)
y_pred_test= model.predict(x_test)

#checking the accuracy_score for train and test

accuracy_train= accuracy_score(y_train, y_pred_train)
accuracy_test= accuracy_score(y_test, y_pred_test)

print("Accuracy score for Train and Test")
print(" ")
print("Accuracy_Train: ",accuracy_train)
print("Accuracy_Test: ",accuracy_test)
print("  ")
#confution matrics and the classification report for test

print("Confution_matrix for Test")
print(" ")
print(confusion_matrix(y_true= y_test, y_pred= y_pred_test))
print(" ")
print("Classification_report for Test")
print(" ")
print(classification_report(y_true= y_test, y_pred= y_pred_test))

Accuracy score for Train and Test
 
Accuracy_Train:  0.9977509711715395
Accuracy_Test:  0.9697465249386754
  
Confution_matrix for Test
 
[[258   0   0   0   1]
 [  0 229   0   0   0]
 [  0   0 235   0   7]
 [  1   0   0 232  10]
 [  1   0   1  16 232]]
 
Classification_report for Test
 
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       259
           1       1.00      1.00      1.00       229
           2       1.00      0.97      0.98       242
           3       0.94      0.95      0.95       243
           4       0.93      0.93      0.93       250

    accuracy                           0.97      1223
   macro avg       0.97      0.97      0.97      1223
weighted avg       0.97      0.97      0.97      1223



In [34]:
print(f"X_train shape: {x_train.shape}")
print(f"y_train shape: {y_train.shape}")

X_train shape: (4891, 10334)
y_train shape: (4891,)


In [35]:
# Random Forest
rf_classifier = RandomForestClassifier()
rf_classifier.fit(x_train, y_train)

RandomForestClassifier()

In [103]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': [1, 0.1, 0.01, 0.001],
    'kernel': ['rbf', 'poly', 'sigmoid']
}

grid = GridSearchCV(SVC(), param_grid, refit=True, verbose=2)
grid.fit(x_train, y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   5.1s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   4.2s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   4.4s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   4.5s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   4.0s
[CV] END ........................C=0.1, gamma=1, kernel=poly; total time=   7.1s
[CV] END ........................C=0.1, gamma=1, kernel=poly; total time=   8.2s
[CV] END ........................C=0.1, gamma=1, kernel=poly; total time=   7.4s
[CV] END ........................C=0.1, gamma=1, kernel=poly; total time=   7.6s
[CV] END ........................C=0.1, gamma=1, kernel=poly; total time=   7.2s
[CV] END .....................C=0.1, gamma=1, kernel=sigmoid; total time=   4.0s
[CV] END .....................C=0.1, gamma=1, k

[CV] END ....................C=1, gamma=0.01, kernel=sigmoid; total time=  10.9s
[CV] END ....................C=1, gamma=0.01, kernel=sigmoid; total time=  10.0s
[CV] END ....................C=1, gamma=0.01, kernel=sigmoid; total time=  10.9s
[CV] END ....................C=1, gamma=0.01, kernel=sigmoid; total time=  10.7s
[CV] END .......................C=1, gamma=0.001, kernel=rbf; total time=  18.1s
[CV] END .......................C=1, gamma=0.001, kernel=rbf; total time=  18.8s
[CV] END .......................C=1, gamma=0.001, kernel=rbf; total time=  17.6s
[CV] END .......................C=1, gamma=0.001, kernel=rbf; total time=  18.0s
[CV] END .......................C=1, gamma=0.001, kernel=rbf; total time=  17.7s
[CV] END ......................C=1, gamma=0.001, kernel=poly; total time=  18.4s
[CV] END ......................C=1, gamma=0.001, kernel=poly; total time=  17.4s
[CV] END ......................C=1, gamma=0.001, kernel=poly; total time=  17.8s
[CV] END ...................

[CV] END ......................C=100, gamma=0.1, kernel=poly; total time=   6.6s
[CV] END ......................C=100, gamma=0.1, kernel=poly; total time=   7.1s
[CV] END ...................C=100, gamma=0.1, kernel=sigmoid; total time=   1.2s
[CV] END ...................C=100, gamma=0.1, kernel=sigmoid; total time=   1.2s
[CV] END ...................C=100, gamma=0.1, kernel=sigmoid; total time=   1.2s
[CV] END ...................C=100, gamma=0.1, kernel=sigmoid; total time=   1.2s
[CV] END ...................C=100, gamma=0.1, kernel=sigmoid; total time=   1.2s
[CV] END ......................C=100, gamma=0.01, kernel=rbf; total time=   1.3s
[CV] END ......................C=100, gamma=0.01, kernel=rbf; total time=   1.3s
[CV] END ......................C=100, gamma=0.01, kernel=rbf; total time=   1.2s
[CV] END ......................C=100, gamma=0.01, kernel=rbf; total time=   1.3s
[CV] END ......................C=100, gamma=0.01, kernel=rbf; total time=   1.3s
[CV] END ...................

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100], 'gamma': [1, 0.1, 0.01, 0.001],
                         'kernel': ['rbf', 'poly', 'sigmoid']},
             verbose=2)

In [104]:
print(f'Best Parameters: {grid.best_params_}')
print(f'Best Score: {grid.best_score_}')

Best Parameters: {'C': 10, 'gamma': 1, 'kernel': 'rbf'}
Best Score: 0.983437880563406


In [105]:
# SVC
svc_classifier = SVC()
svc_classifier.fit(x_train, y_train)

SVC()

In [106]:
new_text = ["lacs lacs standalone consolidated sr particulars st march st march st march st march assets noncurrent assets property plant equipment b capital work progress c intangible assets financial assets noncurrent investments ii loans iii financial assets e noncurrent assets total noncurrent assets current assets inventories b financial assets trade receivables ii cash cash equivalents iii bank balances ii ivj loans v financial assets c current assets total current assets b total assets b b equity liabilities equity equity share capital b equity total equity liabilities noncurrent liabilities financial liabilities long term borrowings ii non current financial liability bj long term provisions c deferred tax liabilities net total noncurrent liabilities b current liabilities financial liabilities short term borrowings ii trade payables iii current financial liabilities b current liabilities cshort term provisions current tax liabilities net total current liabilities c total equity liabilities b c"]
new_X = tfidf_vectorizer.transform(new_text)  
predictions = svc_classifier.predict(new_X)
if predictions == 0:
    print("Balance Sheets")
elif predictions == 1:
    print("Cash Flow")
elif predictions == 2:
    print("Income Statement")
elif predictions == 3:
    print("Notes")
elif predictions == 4:
    print("Others")

Balance Sheets


In [41]:
#saving the vectorizer model using the pickle
with open("tfidf_vectorizer_1.pkl", "wb") as f:
    pickle.dump(tfidf_vectorizer, f)

In [42]:
#loading the vectorizer model
with open("C:\\Users\\hp\\tfidf_vectorizer_1.pkl", "rb") as f2:
    tfidf_vectorizer = pickle.load(f2)

In [63]:
tfidf_vectorizer

TfidfVectorizer()

In [85]:
def extract_text_from_html(html_file):
    with open(html_file, 'r', encoding='utf-8') as file:
        soup = BeautifulSoup(file, 'html.parser')
        text = soup.get_text(separator=' ')
    return text

def clean_text(text):
    # Remove HTML tags
    text = BeautifulSoup(text, "html.parser").get_text()

    # Remove non-alphanumeric characters and convert to lowercase
    text = re.sub(r'[^a-zA-Z\s]', '', text.lower())

    # Tokenize the text
    tokens = nltk.word_tokenize(text)

    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [token for token in tokens if token not in stop_words]

    # Join tokens back into a single string
    clean_text = ' '.join(tokens)

    return clean_text

def embed_text(text):
    with open("C:\\Users\\hp\\tfidf_vectorizer_1.pkl","rb") as f2:
        tfidf_vectorizer = pickle.load(f2)
    
    text_new = tfidf_vectorizer.transform([text])
    return text_new

def predict_category(text_new):

    # Load the model
    with open("C:\\Users\\hp\\Category_Classification_model_1.pkl","rb") as f1:
        class_model= pickle.load(f1)
    
    predictions = class_model.predict(text_new)
    if predictions == 0:
        pred = "Balance Sheets"
    elif predictions == 1:
        pred = "Cash Flow"
    elif predictions == 2:
        
        pred = "Income Statement"
    elif predictions == 3:
        pred = "Notes"
    elif predictions == 4:
        pred = "Others"

    return pred

In [90]:
file_path= "C:\\Users\\hp\\Documents\\data\\data\\Notes\\18599651_table_126.html"
ext_text = extract_text_from_html(file_path)
text_new = clean_text(ext_text)
text=embed_text(text_new)
category = predict_category(text)
print(category)

Notes


In [109]:
#saving the model using the pickle
with open("Findoc_Classification_model.pkl","wb") as f:
    pickle.dump(svc_classifier,f)

In [110]:
with open("C:\\Users\\hp\\Findoc_Classification_model.pkl","rb") as f1:
  class_model_svc= pickle.load(f1)

In [111]:
class_model_svc

SVC()

In [112]:
user_data=["quarter ended year ended particulars audited unaudited audited audited audited revenue operations net sales income operations b license fees service income c operating income total revenue operations income total income expenses cost materials consumed b purchase stockintrade c changes inventories finished goods workinprogress stockintrade employee benefits expense e depreciation amortisation expense f finance costs g selling expenses total expenses profit loss tax tax expense current tax b deferred tax net profit loss period year comprehensive income items reclassified profit loss ii income tax relating items reclassified profit loss b items reclassified profit loss ii income tax relating items reclassified profit loss total comprehensive income total comprehensive income paidup equity share capital face value rs equity earnings per equity share face value rs basic diluted annualised annualised annualised"]
text = tfidf_vectorizer.transform(user_data)  
predictions = class_model_svc.predict(text)
if predictions == 0:
    print("Balance Sheets")
elif predictions == 1:
    print("Cash Flow")
elif predictions == 2:
    print("Income Statement")
elif predictions == 3:
    print("Notes")
elif predictions == 4:
    print("Others")

Income Statement


In [114]:
def extract_text_from_html(html_file):
    with open(html_file, 'r', encoding='utf-8') as file:
        soup = BeautifulSoup(file, 'html.parser')
        text = soup.get_text(separator=' ')
    return text

def clean_text(text):
    # Remove HTML tags
    text = BeautifulSoup(text, "html.parser").get_text()

    # Remove non-alphanumeric characters and convert to lowercase
    text = re.sub(r'[^a-zA-Z\s]', '', text.lower())

    # Tokenize the text
    tokens = nltk.word_tokenize(text)

    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [token for token in tokens if token not in stop_words]

    # Join tokens back into a single string
    clean_text = ' '.join(tokens)

    return clean_text

def embed_text(text):
    with open("C:\\Users\\hp\\tfidf_vectorizer_1.pkl","rb") as f2:
        tfidf_vectorizer = pickle.load(f2)
    
    text_new = tfidf_vectorizer.transform([text])
    return text_new

def predict_category(text_new):

    # Load the model
    with open("C:\\Users\\hp\\Findoc_Classification_model.pkl","rb") as f1:
        class_model= pickle.load(f1)
    
    predictions = class_model.predict(text_new)
    if predictions == 0:
        pred = "Balance Sheets"
    elif predictions == 1:
        pred = "Cash Flow"
    elif predictions == 2:
        
        pred = "Income Statement"
    elif predictions == 3:
        pred = "Notes"
    elif predictions == 4:
        pred = "Others"

    return pred

In [115]:
file_path= "C:\\Users\\hp\\Documents\\data\\data\\Notes\\18599651_table_126.html"
ext_text = extract_text_from_html(file_path)
text_new = clean_text(ext_text)
text=embed_text(text_new)
category = predict_category(text)
print(category)

Notes


In [116]:
file_path= "C:\\Users\\hp\\Documents\\data\\data\\Cash Flow\\18630219_table_52.html"
ext_text = extract_text_from_html(file_path)
text_new = clean_text(ext_text)
text=embed_text(text_new)
category = predict_category(text)
print(category)

Cash Flow
